### ISSUE TITLE
Trader.ts (30,5): Type 'string' is not assignable to type 'number'. (2322)

### ISSUE THREAD

**Issue by donaldforest** [JamesMcMurran/GDaxMarketMakerTrader#7]
How to fix?

```
/lib/node_modules/ts-node/src/index.ts:329
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
Trader.ts (30,5): Type 'string' is not assignable to type 'number'. (2322)
    at getOutput (/lib/node_modules/ts-node/src/index.ts:329:15)
    at Object.compile (/lib/node_modules/ts-node/src/index.ts:515:11)
    at Module.m._compile (/lib/node_modules/ts-node/src/index.ts:402:43)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/lib/node_modules/ts-node/src/index.ts:405:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at Object.<anonymous> (/lib/node_modules/ts-node/src/bin.ts:145:12)
```

**Comment by JamesMcMurran** [comment]
I am not sure where you got this error from I don't have an Index.ts in my code.  It looks like a type miss assignment and you should change what you are trying to put into the variable to a number before putting it in there.
